### ISSUE TITLE
Unable To Recognize Text

### ISSUE THREAD

**Issue by gudimallaHari** [Anyline/anyline-ocr-xamarin-module#11]
Hi,

We are trying to implement vertical character recognition in our product in Xamarin forms. We came across your solution to detect the characters. So i had checked with this solution and able to successfully build the solution. When i run the solution, initially a camera  page was opened. But when i am trying to detect the text using this sample, a rectangular overlay was appearing, but it was not stable and it was unable to detect text. I am attaching sample files for this. Can you please help me on this. 
![Screenshot1](https://user-images.githubusercontent.com/35526061/61703651-abf57780-ad5f-11e9-8621-ed1c03783b54.PNG)
![Capture2](https://user-images.githubusercontent.com/35526061/61703654-ac8e0e00-ad5f-11e9-8d26-cdf54db3f9a5.PNG)

If not can you provide me a sample to detect the vertical text. Thanks for your help.

**Comment by peterAnyline** [comment]
Hello, what exactly are you trying to scan?

**Comment by gudimallaHari** [comment]
![Capture](https://user-images.githubusercontent.com/35526061/61711887-c127d180-ad72-11e9-83fc-396bf4859663.PNG)

Hi peter,

We were trying to scan this particular vertical text in this image.

**Comment by peterAnyline** [comment]
For this, you can try using the following configuration: https://github.com/Anyline/anyline-ocr-xamarin-module/blob/master/Examples/AnylineExamples.Droid/Assets/mro_config_shipping_container.json

but instead of "horizontal", type "vertical" for the container config. You can quickly try this out with our Xamarin.Android example where you just change this one parameter in the json config. Does this work for you?

**Comment by gudimallaHari** [comment]
As you mentioned, i copied the code from "mro_config_shipping_container.json" and created a new ".json" file with same name and content in it. I have also changed the parameter to vertical. When i deployed, a vertical overlay was appearing on camera screen but it is unable to recognize the characters. 
![Capture](https://user-images.githubusercontent.com/35526061/61714499-9e98b700-ad78-11e9-8b79-334fb8aaabc7.PNG)

**Comment by gudimallaHari** [comment]
Hi Peter, any update on this. We are planning to go for license

**Comment by peterAnyline** [comment]
Hello,

please write us via our HelpDesk portal so we can get in direct contact with you and help you solve the issue: https://9yards.atlassian.net/servicedesk/customer/portal/2/group/6/create/18

Thank you!
