### ISSUE TITLE
CI Automation

### ISSUE THREAD

**Issue by slang25** [Anyline/anyline-ocr-xamarin-module#12]
At the moment it looks like to build this module you need a Windows machine, and an SSH connection to a macOS box.

It would be great if there a CI job that ran, so that people forking it could rapidly get a to point where they are producing a custom package. I have done this in our private Azure DevOps, but I don't think it's 100% there as I think it's skipped a step or 2 on iOS.

It could be Azure Pipelines, Travis CI, AppVeyor, etc...

**Comment by rricarrdo** [comment]
Hello, Stuart!
Sorry for the big delay on this issue!

Starting on Anyline 18 we included a Fix for the resource-loading problem when running PackageReference projects directly on macOS.
With this fix, it is now possible to build the projects consuming the AnylineSDK via CI, using for example this command:

```
msbuild /p:Configuration="Release" \
	      /p:Platform="iPhone" \
              /p:IpaPackageDir="$WORKSPACE/" \
              /p:BuildIpa=true \
              /t:Build "Examples/AnylineExamples.iOS/AnylineExamples.iOS.csproj"
```

Can you please confirm if this fix addresses this issue?

Thank you very much for your colaboration!

**Comment by ricardocolombo** [comment]
Hello, Stuart! 

Since we have heard from you in a while, I will close the issue for now. 
If you still face issues in this matter, please don't hesitate to open a new issue. 

Best regards,
