### ISSUE TITLE
AnylineXamarinSDK v19 Release failed

### ISSUE THREAD

**Issue by valerii-sovytskyi** [Anyline/anyline-ocr-xamarin-module#23]
**Description**
Hi, after updating Anyline from v18.1 to v19 I faced an issue when building a release version on AppCenter of Xamarin.Forms ios client application.
Everything works fine on debug mode 

Here is an error from AppCenter
`  MTOUCH : error MT2101: Can't resolve the reference 'ObjCRuntime.TrampolineBlockBase', referenced from the method 'System.Void AnylineXamarinSDK.iOS.ALCaptureDeviceManager::RequestCameraPermission(System.Action'1<System.Boolean>)' in 'Xamarin.iOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.`

**Platform**
Xamarin.iOS

**Version**
v19.0.0

**Comment by rricarrdo** [comment]
Hello @valerii-sovytskyi!

We are investigating this issue now. 
In the meanwhile, can you tell us which version of Xamarin.iOS and Xcode you are using on AppCenter?

Thank you!

**Comment by valerii-sovytskyi** [comment]
Hi @rricarrdo,
Xamarin.iOS 13.2
Xcode: 11.2.1

**Comment by rricarrdo** [comment]
Thank you for the info!

We are currently able to build our samples app in AppCenter (release, Xamarin.iOS 13.2, Xcode 11.2.1). But there seems to be an issue, in some cases, with Mono.Framework 6.4.0.

Can you try using **Xamarin.iOS 13.8** to build your project and let us know the outcome?

Thank you!

**Comment by valerii-sovytskyi** [comment]
@rricarrdo thanks, I changed and it works
