### ISSUE TITLE
Build AnylineXazmarinSDK.Droid fails

### ISSUE THREAD

**Issue by christophedemey** [Anyline/anyline-ocr-xamarin-module#3]
Hi 

Trying to build the project so i can reference it to the example app which doesnt build because it's missing this reference.
Error is : 
Severity	Code	Description	Project	File	Line	Suppression State
Error		The "CreateLibraryResourceArchive" task failed unexpectedly.
Xamarin.Tools.Zip.ZipIOException: File Jars\anylinesdk-3.13.0.aar is not a ZIP archive
   at Xamarin.Tools.Zip.ZipArchive.Open(String path, FileMode mode, String defaultExtractionDir, Boolean strictConsistencyChecks, IPlatformOptions options)
   at Xamarin.Android.Tasks.CreateLibraryResourceArchive.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()	AnylineXamarinSDK.Droid

**Comment by peterAnyline** [comment]
Hi,

if you have cloned the repository, please check out the latest source code, the file should be Jars\anylinesdk-3.15.0.aar in the AnylineXamarinSDK.Droid project as build target "LibraryProjectZip".

If you just need the compiled SDK, just reference the .dll directly (https://github.com/Anyline/anyline-ocr-xamarin-module/blob/master/AnylineXamarinSDK.Droid.dll)

You can also download the latest release directly here: https://github.com/Anyline/anyline-ocr-xamarin-module/releases/download/v3.15.0/AnylineSDK_Xamarin_3.15.0.ZIP

**Comment by christophedemey** [comment]
Hi Peter

I downloaded the release and the sample is working fine now, thanks!

**Comment by slang25** [comment]
For the next person looking at this issue, you might have not pulled the binaries with `git-lfs`, that was my issue.
