### ISSUE TITLE
If we include Anyline Xamarin SDK(42.0.0) APK size become more almost 70 MB increase in size

### ISSUE THREAD

**Issue by KalyanXamarin** [Anyline/anyline-ocr-xamarin-module#37]
If we are increasing Anyline NuGet version Android APK size also increasing.  Current app size 110MB in that 70MB Anyline SDK only.

**Comment by peterAnyline** [comment]
Thank you for your concern. We are providing ways to exclude any resources that you don't need which in turn gives you the control of reducing your application size - Please have a look here: https://documentation.anyline.com/toc/platforms/xamarin/reduce_app_size.html

**Comment by KalyanXamarin** [comment]
Thanks for prompt response @peterAnyline. Taken reference from this project and solved issue
https://github.com/Anyline/anyline-ocr-xamarin-module/blob/master/Examples/AnylineExamples.Droid/AnylineExamples.Droid.csproj

  <Target Name="FilterAnylineAssets" BeforeTargets="_CreateBaseApkWithAapt2">
    <MSBuild Properties="ModulesToKeep=ocr;barcode;document;energy;id;license_plate;tire" Projects="$(MSBuildProjectFile)" Targets="_RemoveAnylineModules" />
  </Target>
