### ISSUE TITLE
Anyline Xamarin iOS Build fail while I placed optimisation code in .csproj

### ISSUE THREAD

**Issue by KalyanXamarin** [Anyline/anyline-ocr-xamarin-module#38]
I placed below code in .csproj. It is removing many other files and showing build errors in iOS. While in android in worked fine

  <Target Name="FilterAnylineAssets" BeforeTargets="_CreateAssetPackManifest">
    <MSBuild Properties="ModulesToKeep=document" Projects="$(MSBuildProjectFile)" Targets="_RemoveAnylineModules" />
  </Target>

  
<img width="676" alt="Screenshot 2022-12-06 at 7 18 16 AM" src="https://user-images.githubusercontent.com/36136595/205789036-02c37359-b312-455b-9205-a11a53c7a96e.png">

**Comment by KalyanXamarin** [comment]
@peterAnyline  any update

**Comment by ricardocolombo** [comment]
Hi @KalyanXamarin, sorry for the delay. We don't actively monitor the GitHub Issues. 

I will ask you to please raise a support request using the [Anyline Helpdesk](https://anyline.atlassian.net/servicedesk/customer/portal/2/group/6). When raising a support request based on this GitHub Issue, please fill out and include the following information:

> Support request concerning Anyline GitHub Repository: anyline-ocr-xamarin-module

along with any other resource that might be helpful for the analysis of the issue.

Best regards,
Ricardo
