### ISSUE TITLE
Anyline FlashStatus does not change when IOS app goes background and comes back.

### ISSUE THREAD

**Issue by ranasinghen** [Anyline/anyline-ocr-xamarin-module#4]
**Steps to reproduce:**
1. Apple IOS device, Open the app and Start Scanning. (Now camera is open)
2. On Flash light.
3. Click the Home Button. (Application goes to background and Flash light turns off)
4. Click on the application to bring application back.
5. Still scanning view is running, camera is open
**Issue**
Although flash light is off, flash status says its on. 

Please verify. Thank you.

**Comment by ale-anyline** [comment]
Thank you for reporting this issue, we were able to reproduce it and will fix it in our next release.
