### ISSUE TITLE
Build fails for iOS 12

### ISSUE THREAD

**Issue by thomasonb** [Anyline/anyline-ocr-xamarin-module#6]
SDK doesn't work with iOS 12, Apple removed support for stdlibc++ and now requires the use of libc++ so when compiling an app for iOS12 it crashes on build because the native library -lstdc++6.0.9 is not found. A potential workaround is to make the gcc compiler swap out -lstdc++ for -lc++ (this hasn't been tested yet). We tried building without the Anyline SDK in the project and it built fine.

**Comment by peterAnyline** [comment]
Thanks for letting us know! We're going to look into it!

**Comment by thomasonb** [comment]
Any news on this?

**Comment by thomasonb** [comment]
awesome, thank you!

**Comment by thomasonb** [comment]
Do you know about what time a fix will be released? It is currently 10AM EST

**Comment by thomasonb** [comment]
We aren't seeing the update in Nuget.

**Comment by ale-anyline** [comment]
The new release is currently available on GitHub and will be on Nuget by Monday.

**Comment by thomasonb** [comment]
Ok, thank you

**Comment by thomasonb** [comment]
Do you know around what time the Nuget package will be updated today?

**Comment by peterAnyline** [comment]
We're trying to upload the package as we speak, but Nuget has issues with large binaries and the upload fails at 80-90% most of the time. Microsoft support stated that we should "just try again"... We'll let you know once it's done! Sorry for the inconvenience.

**Comment by thomasonb** [comment]
Ok thanks for the quick reply :)

**Comment by peterAnyline** [comment]
3.27 is on nuget! 👍

**Comment by thomasonb** [comment]
awesome, testing a build right now

**Comment by thomasonb** [comment]
I'm still receiving the same error even with 3.27. I tried a straight rebuild after pulling the Nuget package. I tried doing a clean solution then a rebuild, and I tried a manual clean (deleting all bin, obj folders) of the solution. The project still builds when the Anyline SDK is removed from the project.

**Comment by peterAnyline** [comment]
Are you sure that the package is up to date? We've tested this issue in particular with iOS 12 and it built our example app fine. As you can see here https://github.com/Anyline/anyline-ocr-xamarin-module/blob/v3.27/BindingSource/AnylineXamarinSDK.iOS/Anyline.linkwith.cs the linker now uses only c++ and not stdc++ any more.. can you post a specific log with the failure message?

**Comment by thomasonb** [comment]
Yeah, I can get the log for you. Maybe a cache thing? I'm not sure where xcode stores cache.

**Comment by peterAnyline** [comment]
I believe it's in your xcode under window -> devices

**Comment by thomasonb** [comment]
I believe this is a cacheing issue, the other developer was able to get a build working on his side, sorry for the confusion, I'll follow up if there are other issues. Thank you.

**Comment by peterAnyline** [comment]
Thank you for the update! Maybe restarting the machine(s) + removing the build from the mtbs folder on the build host will fix this for you!

**Comment by thomasonb** [comment]
Just a follow up, this is working now as expected. I was having an issue on my side, Visual Studio told me it updated the package to 3.27 but it actually failed, after restarting VS I was able to see the package actually didn't update and did an update and it worked.

**Comment by peterAnyline** [comment]
Thanks for letting us know!
