### ISSUE TITLE
3.27.0 Issue

### ISSUE THREAD

**Issue by zacharytomlinson** [Anyline/anyline-ocr-xamarin-module#8]
With the release of 3.27.0, the scanner fails at self.view addSubview:self.licensePlateModuleView]; in Xamarin.Forms for iOS.

**Comment by peterAnyline** [comment]
Hello! Could you provide some sort of error log or information?

**Comment by zacharytomlinson** [comment]
2018-10-08 17:05:44.299 AuctionTracUK.iOS[530:46651] AnylineSDK Version 3.26.0 (1369)
2018-10-08 17:05:44,322744 anyline_core.cpp:85 WARNING: This license is valid until: 2018-11-07
The app has been terminated.
Failed to Stop app:  An error occured on client IDB4110776 while executing a reply for topic xvs/idb/4.11.0.776/stop-app
The app has been terminated.

This is the standard output, but one time I got:

libc++abi.dylib: terminating with unexpected exception of type std::__1::system_error: mutex lock failed: Invalid argument

Which made it sound like it was an issue with compiling with libc++ as opposed to libstdc++

**Comment by zacharytomlinson** [comment]
The version name in the output says 3.26 but I can assure you it is 3.27

**Comment by peterAnyline** [comment]
This might be a caching issue (due to the 3.26 in the output) - please clean the \bin and \obj folders of your project and remove the mtbs folder on your mac build host (~\Library\Caches\Xamarin\builds\mtbs) and check if that issue still persists

**Comment by zacharytomlinson** [comment]
I did just this and the issue persisted. The output still references 3.26

**Comment by peterAnyline** [comment]
Could you try to remove the AnylineXamarinSDK.iOS.dll from your references, remove the AnylineResources.bundle, download the zip from https://github.com/Anyline/anyline-ocr-xamarin-module/releases/download/v3.27.0/AnylineSDK_Xamarin_3.27.0.ZIP and include the dll and resources as described here: https://documentation.anyline.com/toc/platforms/xamarin/xamarin.ios/xamarin.ios_quickstart.html ?

**Comment by zacharytomlinson** [comment]
After updating the AnylineResources.bundle, the scanner works as expected. For some reason the Nuget package update did not update the resources. Thank you sir!

**Comment by peterAnyline** [comment]
Thanks for letting us know! I'm glad it works now!
